package com.atguigu.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.d_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private String dName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.d_id
     *
     * @return the value of t_dept.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.d_id
     *
     * @param dId the value for t_dept.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.d_name
     *
     * @return the value of t_dept.d_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.d_name
     *
     * @param dName the value for t_dept.d_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }
}