package com.atguigu.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.e_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private Integer eId;

    @Override
    public String toString() {
        return "Emp{" +
                "eId=" + eId +
                ", eName='" + eName + '\'' +
                ", sex='" + sex + '\'' +
                ", age=" + age +
                ", dId=" + dId +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.e_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.sex
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.age
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.e_id
     *
     * @return the value of t_emp.e_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.e_id
     *
     * @param eId the value for t_emp.e_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.e_name
     *
     * @return the value of t_emp.e_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.e_name
     *
     * @param eName the value for t_emp.e_name
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.sex
     *
     * @return the value of t_emp.sex
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.sex
     *
     * @param sex the value for t_emp.sex
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.age
     *
     * @return the value of t_emp.age
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.age
     *
     * @param age the value for t_emp.age
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.d_id
     *
     * @return the value of t_emp.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.d_id
     *
     * @param dId the value for t_emp.d_id
     *
     * @mbggenerated Fri Mar 04 09:30:08 CST 2022
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}